name: MacOS X

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: build
      run: |
        cd test
        make

    - name: test
      run: |
        cd test
        ./test

# vi:ts=2 sts=2 sw=2 expandtab:
